### ISSUE TITLE
[api] document conflict resolution

### ISSUE THREAD

**Issue by andrenarchy** [libremesh/libremap#1]
If documents are updated on several CouchDB servers at once, then document may conflict, see the [couchdb guide](http://guide.couchdb.org/editions/1/en/conflicts.html). The conflict has to be resolved from the outside, e.g. the submitting agent or a maintenance script.

**Comment by nicopace** [comment]
@andrenarchy although this is something that could happen, in practice as the information that is submitted is naturally shardened by being geolocation-related, this issue wouldn't happen.

Please could you provide a concrete user case where this may arise?
Once we have extra feedback you can reopen the issue and altogether deal with the issue.

Thanks!
