### ISSUE TITLE
[api] gather router history

### ISSUE THREAD

**Issue by andrenarchy** [libremesh/libremap#5]
Determine possibilities of storing a router's history when it is updated.
## Possibilities
- push _history_ document from router.
- push _history_ document by listening on CouchDB's __changes_ feed.
## Questions
- will history be replicated?
- aggregation of history (as in RRDtool)?

**Comment by nicopace** [comment]
Hi @andrenarchy. I'm doing some cleanup and this issue seems really old.
Is it still relevant? I will close the issue, and if you believe it is relevant, we open it again ad can you give a little more context to push it forward?
Thanks!
