### ISSUE TITLE
[webui] restructure code

### ISSUE THREAD

**Issue by andrenarchy** [libremesh/libremap#7]
e.g. requirejs, browserify?

**Comment by elf-pavlik** [comment]
i would like to also make it possible to work on webui using online dev couch so someone doesn't need to go through all the couchdb+geocouch setup just to fix some stuff in ui :)

i can help with this issue here sometimes next week!

**Comment by elf-pavlik** [comment]
please check out this video of neat presentation on http://browserify.org --  https://vimeo.com/62988591

**Comment by andrenarchy** [comment]
alright, now I'm totally convinced by browserify and grunt. :smile: I started a branch _webui-restructure_ and pushed my first steps with grunt.

@elf-pavlik: do you have some time to assist me? Perhaps it's a no-brainer for you while it would take me several hours...

I was thinking about the following structure and features below `/webui/`:
- `/src`: only actual code (index.html, css, images, js, html templates) written for libremap (dependencies should be taken care of npm/grunt)
- `/template_ddoc`: template for the couchdb design doc
- `/build`: static files (index.html, css, images), concatenated templates and browserify'd and maybe uglified js code ends up here
  - there's only one js file `/build/bundle.js`
- is it possible to pass options to grunt? examples:
  - enable uglify
  - add --debug to browserify
  - set libremap api url
  - flag for building couchdb design doc (there's a `grunt-couch` and `grunt-couchapp` package in npm)
  - push design doc to a couchdb

@elf-pavlik: what do you think? I'd be thrilled if you have some spare time and could push things forward with a PR for the _webui-restructure_ branch. :smile:

**Comment by elf-pavlik** [comment]
@andrenarchy just arrived to Munich and will hitchhike to Graz tomorrow or day after!

for now please check out how i use grunt in: https://github.com/elevate-festival/neokarto-party/blob/master/Gruntfile.js

we can get on it together one of the days this week, tomorrow i will know more :smile:

**Comment by elf-pavlik** [comment]
@andrenarchy as i mentioned before i would also like to make development of front end app independent from api so one doesn't need to run couchdb or push app to it for **development**!

we can still write dedicated task for **production** deployment which will take care of doing the couchapp thing...

**Comment by andrenarchy** [comment]
Done, see https://github.com/libremap/libremap-webui and https://github.com/libremap/libremap-api
